### ISSUE TITLE
How to integrate with existing react-toolbox project

### ISSUE THREAD

**Issue by Kannaj** [javivelasco/react-css-themr#1]
Do you have an example explaining how to integrate css-themr with an existing react-toolbox project?

**Comment by javivelasco** [comment]
Not yet, I'm working on a branch to do the integration for the next release. I'll try to have it ready during this weekend. The idea is to provide some functions to make easier the customization from context instead of using the raw package. The toolbox-loader approach would still work but you'd need to import and inject in the context the css for used components.

**Comment by Kannaj** [comment]
the current problem as you previously mentioned in the react-toolbox page is over-riding the default css themes .. its getting a bit cumbersome to add '!important' to custom css files .. css-themr sounds like a life saver :) .. please let me know if i can help you in anyway to speed things up

**Comment by javivelasco** [comment]
Thanks for your offering. I think I will have it ready by the weekend. I plan to release a new version including it for then, it would improve the way react toolbox is customized! :)

**Comment by davidvictor** [comment]
any update on this? would love to be able to begin implementing this approach as soon as possible. Context theming react-toolbox will save my current project from maintenance issues down the road.

**Comment by javivelasco** [comment]
Still working on it!

**Comment by javivelasco** [comment]
Closing since it's done!
