### ISSUE TITLE
Only for CSS Modules/Class names?

### ISSUE THREAD

**Issue by NogsMPLS** [javivelasco/react-css-themr#2]
Is the scope for this project just for sending in class names down for theme styles?

Just curious if things like style objects/inline styles/radium are also on your mind for this project, or if that would be out of the realm of what this decorator should handle.

**Comment by javivelasco** [comment]
Yeah it could be great to support all kind of approaches to styling. I've made the module to use it at work and for React Toolbox. In both cases I'm using CSS modules and I have no experience with Radium etc, so I'd be happy to discuss how to implement it but for now I have no clue.

**Comment by javivelasco** [comment]
@NogsMPLS did you have any idea on how can we integrate with inline styles approaches out there? Probably just allowing to merge style objects could be a step forward assuming you'll use the `theme` prop to inject styles in `style` props rather than `classNames`. Also I think there should be a priority on merging. For example inline > default > context.

**Comment by Podlas29** [comment]
Maybe you could pass theme like so:
```javascript
<Component {...this.props.theme} /* some other props */ />
```
And then library under the hood would inject either `{style}` or `{className}` object, depending on mode in which it operates.
Then if you would have components library and decided to switch from css modules to inline, you would not have to touch components at all! 

Have great day everyone!

**Comment by raveclassic** [comment]
@Podlas29 Such approach (hiding theme processing in the lib) would also hide all possibilities to modify whole theme object in an intermediate component and passing modified theme/parts of theme to its children. Moreover it would increase amount of hidden logic and add much more complexity to handling cases when style and className props are passed to decorated component.

What about inlining I think theme merging can be abstracted from themr core to some drop in strategy to support different ways to process theme keys so that the values could be either string classnames or objects of style rules or anything other. Then you could specify it when decorating a component so that it only accepts theme values of one type classnames, styles, etc). Themr HOC could also check theme object received via props or context to be of specified type in propTypes.
