### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by UX-Unicorn** [javivelasco/react-css-themr#58]
I am getting the following warning when upgrading React 15.5. Is there plans to fix this?

**Comment by raveclassic** [comment]
The fix is very simple: according to official docs, propTypes should be imported from separate package. But unfortunately it seems that @javivelasco last time reviewed react-css-themr long time ago, there are still pending changes in master branch to be released and some open pullrequests. Until he takes a look there's no way to release this fix.

**Comment by javivelasco** [comment]
Updated already, releasing today!
